name = "yumezone-worker"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
account_id = ""
zone_id = ""
route = ""

[build]
command = ""
cwd = ""

[build.upload]
format = "service-worker"
main = "./index.js"
